### PR TITLE
Set up GitHub Actions

### PR DESCRIPTION
**Pull request by Goooler**
See https://github.com/Goooler/kotlin-explorer/actions/runs/7510333742/job/20448621772.

### CODE REVIEW

**Review by romainguy — COMMENTED** [review]
Why does this need a new plugin?

**Comment by Goooler** [comment]
> https://github.com/Goooler/kotlin-explorer/actions/runs/8399957453/job/23006686932
> * What went wrong:
Could not determine the dependencies of task ':compileKotlinJvm'.
> No matching toolchains found for requested specification: {languageVersion=17, vendor=JETBRAINS, implementation=vendor-specific} for LINUX on x86_64.
   > No locally installed toolchains match and toolchain download repositories have not been configured.


Add this plugin to ensure downloading proper Jetbrains JDKs, we can remove this plugin after removing 
https://github.com/romainguy/kotlin-explorer/blob/cacd3b68bab8ce6f9021e83595a63673d1ddd9f0/build.gradle.kts#L19
https://github.com/romainguy/kotlin-explorer/blob/cacd3b68bab8ce6f9021e83595a63673d1ddd9f0/build.gradle.kts#L27

**Comment by romainguy** [comment]
No, we can’t remove those, this runtime is necessary.

**Comment by Goooler** [comment]
So we need this plugin now, JBR vendor setups are blocked by https://github.com/actions/setup-java/issues/399.

**Review by romainguy — APPROVED** [review]

**Pull request merged**
